# Site settings
title: Binary.com Developers
url: "https://developers.binary.com"
twitter_username: binarydotcom
github_username:  binary-com

# Build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /web
    baseurl: tahmi123.github.io/web
