# Site settings
title: Binary.com Developers
url: "https://tahmi123.github.io/web"
twitter_username: binarydotcom
github_username:  binary-com

# Build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: ""
    
